---
title: "NFL Weekly attendance"
author: "edgar M"
date: "2023-12-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tidyverse)
library(tidymodels)
```

#Data Download

```{r message=FALSE, warning=FALSE}

attendance <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/attendance.csv")
standings <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv")

```

```{r}
attendance_joined <- attendance %>%
  left_join(standings,
            by = c("team_name", "year"))

```

```{r}
#Exploring

attendance_joined %>%
  filter(!is.na(weekly_attendance)) %>%
  ggplot(aes(fct_reorder(team_name, weekly_attendance),
             weekly_attendance,
             fill = playoffs)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
attendance_joined %>%
  distinct(team_name, playoffs, margin_of_victory, weekly_attendance) %>%
  ggplot(aes(margin_of_victory, fill = playoffs)) +
  geom_histogram()

```

```{r}
#select columns used in training
attendance_df <- attendance_joined %>%
  filter(!is.na(weekly_attendance)) %>%
  select(team_name, week, year, playoffs, margin_of_victory, weekly_attendance,
         strength_of_schedule)
```

```{r}
#Training and testing

nfl_data <- initial_split(attendance_df, strata = playoffs)

nfl_train <- training(nfl_data)
nfl_test <- testing(nfl_data)

```

```{r}
#set engine for lm and rf 

lm_spec <- linear_reg() %>%
  set_engine(engine = "lm")

lm_fit <- lm_spec %>%
  fit(weekly_attendance ~ ., data = nfl_train)

rf_spec <- rand_forest("regression") %>%
  set_engine("ranger")

rf_fit <- rf_spec %>%
  fit(weekly_attendance~ ., data = nfl_train)
```

```{r}
#Evaluation
result_train <- rf_fit %>%
  predict(new_data = nfl_train) %>%
  mutate(truth = nfl_train$weekly_attendance,
         model = "rf") %>%
  bind_rows(lm_fit %>%
              predict(new_data = nfl_train) %>%
              mutate(truth = nfl_train$weekly_attendance,
                     model = "lm"))

```

```{r}
result_test <- rf_fit %>%
  predict(new_data = nfl_test) %>%
  mutate(truth = nfl_test$weekly_attendance,
         model = "rf") %>%
  bind_rows(lm_fit %>%
              predict(new_data = nfl_test) %>%
              mutate(truth = nfl_test$weekly_attendance,
                     model = "lm"))
  
```

```{r}
result_test %>%
  group_by(model) %>%
  rmse(truth = truth, estimate = .pred)


```

```{r}
result_train %>%
  group_by(model) %>%
  rmse(truth = truth, estimate =.pred)
```

```{r}
#set seed
set.seed(3456)
nfl_folds <- vfold_cv(nfl_train, strata = playoffs)

rf_res <- fit_resamples(
  rf_spec,
  weekly_attendance ~ .,
  nfl_folds,
  control = control_resamples(save_pred = TRUE)
)

```

```{r}
rf_res %>%
  collect_metrics()
```

\
